### ISSUE TITLE
Typo in link to file

### ISSUE THREAD

**Issue by millerjamesg** [5etools-mirror-3/5etools-src#1]
https://github.com/5etools-mirror-3/5etools-src/blob/6305a1f36c8af9fe516c435c776904ddf5890ebe/data/adventure/adventure-uthftlh.json#L1858

Is this a bug or a feature request: Bug

Issue: This line of code links to the file "pdf/UtHftLH/niko-character-sheet.pdf" from the "5etools-img" repository, however, in that repository, the file is called "pdf/UtHftLH/nikos-character-sheet.pdf" ('s' in 'nikos').

Page(s) affected: https://5e.tools/adventure.html#uthftlh,1

Reproduction steps: Navigate to the page linked, click the "Niko" link for the pdf character sheet. 404.

Additional information: I absolutely love your work :)

Browser (Chromium, Firefox, Edge, etc): Firefox 130.0.1 64-bit

Platform (Windows, iOS, Android, etc): Linux Mint 21.1

**Comment by TheGiddyLimit** [comment]
fixed for next release
