### ISSUE TITLE
Fix: Eldritch invocation on PHB'14

### ISSUE THREAD

**Issue by jordyalcides** [5etools-mirror-3/5etools-src#5]
The correct Eldritch Invocations according to PHB'14 is 
`"progression": [0,2,2,3,3,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8]`

https://github.com/5etools-mirror-3/5etools-src/blob/2f38bfcd66c8b6062c94c2bf2bc8df56d0204bfc/data/class/class-warlock.json#L96C7-L96C9

**Comment by TheGiddyLimit** [comment]
doesn't look that way to me:

![image](https://github.com/user-attachments/assets/d9a99568-9d22-4925-b6a6-0b9a8583aa09)

**Comment by jordyalcides** [comment]
Sorry, I just noticed that I was looking in a translated version of the PHB, probably the mistake was made in the translation process.

**Comment by TheGiddyLimit** [comment]
all good
