### ISSUE TITLE
DM Screen crashes after a few minutes.

### ISSUE THREAD

**Issue by imbabaer** [5etools-mirror-3/5etools-src#7]
Is this a bug or a feature request:
Bug

Issue:
After a few minutes (2-5) the DM Screen crashes and i get the Chrome error message:
"Aw, snap! Something went wrong while displaying this website. Error Code 5."
<img width="720" alt="image" src="https://github.com/user-attachments/assets/9510beab-4bc7-4788-a590-b9621344b46c">
There are no logs in the Console.log.

Page(s) affected:
https://5e.tools/dmscreen.html

Reproduction steps:

1. Open presaved DM Screen.
2. Wait some time (2-5 min).

Link to my saved DM Screen:
`https://5e.tools/dmscreen.html#%7B"w"%3A3%2C"h"%3A3%2C"ctc"%3Afalse%2C"fs"%3Afalse%2C"lk"%3Afalse%2C"ps"%3A%5B%7B"x"%3A0%2C"y"%3A1%2C"w"%3A1%2C"h"%3A1%2C"t"%3A0%7D%2C%7B"x"%3A1%2C"y"%3A2%2C"w"%3A1%2C"h"%3A1%2C"t"%3A0%7D%2C%7B"x"%3A1%2C"y"%3A1%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"panther_mm"%7D%2C"a"%3A%5B%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"berserker_mm"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"cave%2520bear_mm"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"veteran_mm"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"panther_mm"%7D%7D%5D%2C"b"%3A3%7D%2C%7B"x"%3A1%2C"y"%3A0%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"cultist_mm"%7D%2C"a"%3A%5B%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"cultist_mm"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"LMoP"%2C"u"%3A"evil%2520mage_lmop"%7D%7D%5D%2C"b"%3A0%7D%2C%7B"x"%3A0%2C"y"%3A2%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"tables.html"%2C"s"%3A"DMG"%2C"u"%3A"random%2520dungeon%2520hazards%253b%2520dungeon%2520hazards_dmg"%7D%2C"a"%3A%5B%7B"t"%3A1%2C"c"%3A%7B"p"%3A"tables.html"%2C"s"%3A"DMG"%2C"u"%3A"random%2520dungeon%2520hazards%253b%2520dungeon%2520hazards_dmg"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"tables.html"%2C"s"%3A"DMG"%2C"u"%3A"random%2520traps%253b%2520trap%2520effects_dmg"%7D%7D%5D%2C"b"%3A0%7D%2C%7B"x"%3A0%2C"y"%3A0%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"veteran_mm"%7D%2C"a"%3A%5B%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"scout_mm"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"veteran_mm"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"bandit%2520captain_mm"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"GoS"%2C"u"%3A"pirate%2520captain_gos"%7D%7D%5D%2C"b"%3A1%7D%2C%7B"x"%3A2%2C"y"%3A2%2C"w"%3A1%2C"h"%3A1%2C"t"%3A5%2C"s"%3A%7B"s"%3A"NUMBER"%2C"d"%3A"DESC"%2C"ri"%3Atrue%2C"m"%3Afalse%2C"rg"%3Afalse%2C"rri"%3Afalse%2C"g"%3Atrue%2C"p"%3Atrue%2C"a"%3Afalse%2C"k"%3Afalse%2C"piHp"%3Afalse%2C"piHm"%3Afalse%2C"piV"%3Atrue%2C"piO"%3Afalse%2C"c"%3A%5B%5D%2C"cndc"%3A%5B%5D%2C"r"%3A%5B%7B"id"%3A"f91d3360-0028-4f8f-b6f8-8e0c3c0d0c6d"%2C"n"%3A"Displacer Beast"%2C"h"%3A85%2C"g"%3A85%2C"i"%3A20%2C"a"%3Afalse%2C"s"%3A"MM"%2C"c"%3A%5B%5D%2C"v"%3A0%2C"o"%3A1%2C"k"%3A%5B%5D%7D%2C%7B"id"%3A"85d25272-8d53-4fcd-a1fc-ec7c7bea861a"%2C"n"%3A"ar"%2C"i"%3A18%2C"a"%3Afalse%2C"c"%3A%5B%5D%2C"v"%3Atrue%2C"o"%3A1%2C"k"%3A%5B%5D%7D%2C%7B"id"%3A"7f1d9bc2-f7ed-4b18-9a6a-dd388270e382"%2C"n"%3A"fra"%2C"i"%3A14%2C"a"%3Afalse%2C"c"%3A%5B%5D%2C"v"%3Atrue%2C"o"%3A1%2C"k"%3A%5B%5D%7D%2C%7B"id"%3A"eb6732d7-45a0-4089-b63c-07339d8f7910"%2C"n"%3A"elo"%2C"i"%3A12%2C"a"%3Atrue%2C"c"%3A%5B%5D%2C"v"%3Atrue%2C"o"%3A1%2C"k"%3A%5B%5D%7D%2C%7B"id"%3A"9270a0ed-f77c-4ff9-b92c-25e483a15602"%2C"n"%3A"ele"%2C"i"%3A8%2C"a"%3Afalse%2C"c"%3A%5B%5D%2C"v"%3Atrue%2C"o"%3A1%2C"k"%3A%5B%5D%7D%2C%7B"id"%3A"caeeaa24-8f8c-4e7e-9844-c181bd63d21d"%2C"n"%3A"mig"%2C"i"%3A2%2C"a"%3Afalse%2C"c"%3A%5B%5D%2C"v"%3Atrue%2C"o"%3A1%2C"k"%3A%5B%5D%7D%2C%7B"id"%3A"5998bf3b-74a7-4cc7-b70f-a17bce450fb1"%2C"n"%3A"clink"%2C"a"%3Afalse%2C"c"%3A%5B%5D%2C"v"%3Atrue%2C"o"%3A1%2C"k"%3A%5B%5D%7D%5D%2C"rdp"%3A%5B%5D%2C"n"%3A9%7D%7D%2C%7B"x"%3A2%2C"y"%3A0%2C"w"%3A1%2C"h"%3A2%2C"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"adult%2520red%2520dragon_mm"%7D%7D%5D%2C"ex"%3A%5B%7B"x"%3A3%2C"y"%3A0%2C"w"%3A1%2C"h"%3A2%2C"t"%3A51%2C"s"%3A%7B%7D%7D%2C%7B"x"%3A2%2C"y"%3A0%2C"w"%3A1%2C"h"%3A1%2C"t"%3A90%2C"c"%3A%7B"u"%3A"https%3A%2F%2F5e.tools%2Flootgen.html"%7D%7D%2C%7B"x"%3A2%2C"y"%3A1%2C"w"%3A1%2C"h"%3A1%2C"t"%3A90%2C"c"%3A%7B"u"%3A"https%3A%2F%2F5e.tools%2Fencountergen.html%23grassland_xge_1-5-"%7D%7D%2C%7B"x"%3A2%2C"y"%3A2%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"items.html"%2C"s"%3A"DMG"%2C"u"%3A"staff%2520of%2520the%2520adder_dmg"%7D%7D%2C%7B"x"%3A0%2C"y"%3A1%2C"w"%3A1%2C"h"%3A1%2C"t"%3A16%2C"s"%3A%7B"state"%3A%7B%7D%2C"rowState"%3A%5B%5D%7D%7D%2C%7B"x"%3A0%2C"y"%3A0%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"ogre%2520zombie_mm"%7D%2C"a"%3A%5B%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"zombie_mm"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"ogre%2520zombie_mm"%7D%7D%2C%7B"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"VRGR"%2C"u"%3A"swarm%2520of%2520zombie%2520limbs_vrgr"%7D%7D%5D%2C"b"%3A1%7D%2C%7B"x"%3A0%2C"y"%3A1%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"hell%2520hound_mm"%7D%7D%2C%7B"x"%3A1%2C"y"%3A2%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"gelatinous%2520cube_mm"%7D%7D%2C%7B"x"%3A3%2C"y"%3A2%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"MM"%2C"u"%3A"panther_mm"%7D%7D%2C%7B"x"%3A2%2C"y"%3A0%2C"w"%3A1%2C"h"%3A1%2C"t"%3A1%2C"c"%3A%7B"p"%3A"bestiary.html"%2C"s"%3A"BGG"%2C"u"%3A"barrowghast_bgg"%7D%7D%5D%7D`

Additional information:
I saved the link a few months ago. Perhaps something changed in the link creation or so?
I can only reproduce the crash with my older link, if i start a new DM Screen and let that run, the site runs just fine. 

Browser (Chromium, Firefox, Edge, etc):
Chrome (Version 130.0.6723.70, but appeared also before)

Platform (Windows, iOS, Android, etc):
macOS Sequoia 15.1 (m3 max, 16')

**Comment by TheGiddyLimit** [comment]
Can't repro that here, and I'm not seeing any evidence of e.g. a memory leak which might be eventually causing the crash.

If you go into the sidebar and `Clear` the "Recently Removed" panels, does the issue persist?

**Comment by imbabaer** [comment]
It looks like clearing the "Recently Removed" did the trick. Thanks!
