### ISSUE TITLE
Tooltip Not Found in Demonomicon of Iggwilv

### ISSUE THREAD

**Issue by redgreene** [5etools-mirror-3/5etools-src#8]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: When reading the description text for the "Demonomicon of Iggwilv" item of the 2024 DMG, there is a [Tooltip Not Found] error instead of the section of text intended there. It appears as follows: "This treatise, composed by [Iggwilv](https://5e.tools/book.html#XDMG,8,iggwilv,0) the archmage, documents [Tooltip Not Found] layers and inhabitants and is widely regarded as the most thorough and blasphemous tome of demonology in the multiverse."

Page(s) affected: One known: https://5e.tools/items.html#demonomicon%20of%20iggwilv_xdmg

Reproduction steps: Open link given above.

Additional information: None

Browser (Chromium, Firefox, Edge, etc): Chrome

Platform (Windows, iOS, Android, etc): Windows 10

**Comment by TheGiddyLimit** [comment]
fixed for next release
